/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hsato' at '7/28/16 12:59 PM' with Gradle 2.14
 *
 * @author hsato, @date 7/28/16 12:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
